### ISSUE TITLE
Hook fails to run properly with cordova 6.3.1

### ISSUE THREAD

**Issue by betko** [akofman/cordova-plugin-add-swift-support#14] opened 2016-09-08 13:22 UTC
I'm facing an issue with the plugin when running with: `cordova@6.3.1`. The cordova hook which sets the Bridging Headers and the xcode project properties, is not executed after `cordova prepare`. 

The plugins works properly with `cordova@6.1.1`. 

Modifying the hook condition seems to fix the issue:

``` js
if ((context.hook === 'after_platform_add' && context.cmdLine.includes('platform add')) ||
    (context.hook === 'after_prepare' && context.cmdLine.includes('prepare')) ||
    (context.hook === 'after_plugin_add' && context.cmdLine.includes('prepare')) ||
    (context.hook === 'after_plugin_add' && context.cmdLine.includes('plugin add'))) {
// ...
}
```

If the fix looks okey, I can make a PR. 😸

**Comment by akofman** [comment] 2016-09-09 09:22
Hello @betko, thanks for your help. I'll look at that this weekend and keep you in touch.

**Comment by akofman** [comment] 2016-10-14 15:08
Hello @betko ! Sorry for the laaaaaaaate. You're right and your fix looks fine, PR is welcome.

**Comment by akofman** [comment] 2017-01-09 14:32
I can't reproduce it anymore so I close this issue.
I tried to reproduce with the `cordova-plugin-permissionScope` and `cordova@6.3.1`. 
I removed the `#import "PermissionScope-Bridging-Header.h"` from the `Bridging-Header.h` then run `cordova prepare`, I can see it well configured again as expected.

**Closed by akofman** 2017-01-09 14:32 UTC
