### ISSUE TITLE
Changing hook type

### ISSUE THREAD

**Issue by tabrindle** [akofman/cordova-plugin-add-swift-support#3] opened 2016-04-21 21:11 UTC
Would there be any adverse or unexpected effects of changing the hook type from after_platform_add  to after_plugin_add? We have an app with a sizeable amount of code on the native side and its not practical to generate the ios platform on each checkout.

**Comment by akofman** [comment] 2016-04-22 10:19
Hello,

Once this plugin installed, it executes a script to check the presence of bridging headers in the other plugins of your project. 
In order to do that, it must be installed after all other plugins. That's why the script is executed after the platform is added to be sure all other plugins have already been installed. 
Unfortunately, I tried with an after_prepare hook but it doesn't work with plugins, I'll check that in the Cordova codebase because I think it should work like that.

An after_plugin_add hook would be executed once after adding this plugin. So it won't guaranteed the presence of bridging headers in all other plugins if it is added before them.

In your case, I think the best solution at the moment would be to directly add the `add-swift-support` script as a hook in your project.
Hope it helps.

**Comment by tabrindle** [comment] 2016-04-22 14:00
Thank you very much for the quick response. This is pretty much what I expected, and It seems that calling the script directly works. Thanks!

**Comment by becvert** [comment] 2016-06-08 13:42
Hi @akofman 

an after_prepare hook seems to work but only when you give explicitly the platform to the command

`cordova prepare` doesn't trigger the hook

`cordova prepare ios` does trigger the hook

does it make sense? is there a way to fix that?

Thank you

**Comment by akofman** [comment] 2016-06-08 13:49
Hey @becvert ! Very helpful comment. Thanks for that. 
I'm gonna test it and keep you informed. If it's fine, I will update the hook and the README of this plugin and will check with the Cordova team if it is an expected behaviour.

Thanks again.

**Comment by becvert** [comment] 2016-06-08 13:56
My guess is that you shoudn't wrap the hook inside the `<platform>` element

**Comment by akofman** [comment] 2016-06-08 14:05
Sounds good ! I just have to check if it doesn't throw any error messages in case of a non-ios platform.

**Comment by akofman** [comment] 2016-06-08 20:31
@becvert it's fine to me. If you could have a try with this last commit and confirm everything is also right for you, I'll merge it.

**Comment by becvert** [comment] 2016-06-09 07:43
It's fine to me too

**Comment by akofman** [comment] 2016-06-09 08:38
Thanks ! Merged in version 1.1.0.

**Closed by akofman** 2016-06-09 08:38 UTC

**Comment by becvert** [comment] 2016-06-10 10:27
@akofman
When a plugin dependent of yours is first installed, its header file doesn't get added to the Bridging Header immediately but only on subsequent `prepare`.

which is probably not a problem if you do
`cordova plugin add myplugin`
and then
`cordova prepare`

but in some instances you install plugins from config.xml by calling `cordova prepare ` once. then it fails.
only a subsequent `prepare ` fixes it.
Does it make sense?

I believe now that this hook is better:
```
<hook type="after_plugin_add" src="src/add-swift-support.js" />
```
sorry for the confusion...

**Comment by akofman** [comment] 2016-06-10 10:30
Hmm indeed, I think we could keep both hooks. We'll do that layer.

**Comment by becvert** [comment] 2016-06-10 11:02
that will do :+1: 
thank you

**Comment by akofman** [comment] 2016-06-11 22:43
OK from this [branch](https://github.com/akofman/cordova-plugin-add-swift-support/tree/hooks) I added some hooks and updated the script.

I tested multiple cases : 
- [x] If the platform is added first then this plugin is added.
- [x] If the plugin is added first then the platform.
- [x] If the plugin is configured from the `config.xml`file then the platform is added.
- [x] If an other Swift plugin bundled with a custom Bridging-Header is added then its Bridging-Header is well merged.
- [x] Also I've kept the `after_prepare` hook so that if we are in a case with an already configured platform without the swift support, it will be well added after preparing the platform.

Any objections ?
