### ISSUE TITLE
Support cordova-cli 9.0.0 - requireCordovaModule deprecation

### ISSUE THREAD

**Issue by tombell** [akofman/cordova-plugin-add-swift-support#56] opened 2019-03-25 10:13 UTC
The use of `context.requireCordovaModule` for non-cordova dependencies has been removed, and suggests you now add the dependency to the plugins `package.json` and `require`'d normally.

https://github.com/apache/cordova-lib/pull/707

**Comment by lrbalt** [comment] 2019-03-27 13:12
manually changing `context.requireCordovaModule` into plain `require` gives another error: `context.vaModule is not a function`. This occurs on line 13614 of `add-swift-support.js`: `var glob = context.vaModule('glob');`. Any idea how to fix this?

**Comment by brainssolutions** [comment] 2019-03-27 15:34
@lrbalt The problem is encountered when the new ios@5.0.0 version does not support the required file upload through that command.

Just go to  **"Projectroot\plugins\cordova-plugin-add-swift-support"** and open the file **add-Swift-support. js** replacing the old command:

 "context. requireCordovaModule" with-> require

I also found that on the line:

-> 12920: var cordovaUtil = context. requireCordovaModule (' Cordova-lib/src/Cordova/util ');

While changing the method as shown above, the CLI of Cordoba returns an error. I reset the old variable and added the iOS platform again.

It worked For me.

**Comment by timbru31** [comment] 2019-03-27 18:05
I'm currently working on a PR to update fix this issue (and to update the dependencies and drop webpack)

**Comment by akofman** [comment] 2019-03-27 21:20
Hello guys, 

Thanks a lot for you PR @timbru31, I'm not working on a Cordova project anymore at the moment so it's really appreciated to have this kind of PR. I will have a look on it this week. 
@brainssolutions, @lrbalt and @tombell could you please check the Tim's PR and return me if it works for you ? It will help a lot.

**Comment by tombell** [comment] 2019-03-27 21:31
@akofman Yup, I'll give it a try when I return to work tomorrow 👍

**Comment by lrbalt** [comment] 2019-03-28 08:53
changing all requireCordovaModule with plain require works. I made a typo, so forget about the other error I reported.

**Comment by lrbalt** [comment] 2019-03-28 09:46
I just used PR #57 and my app compiles with latest xcode. I needed to manually set minimum swift version to 4, but I don't know if this plugins depends on swift 3 or another one. I'm in favor of merging

**Comment by akofman** [comment] 2019-03-28 10:43
@lrbalt you should be able to configure this version using `<preference name="UseSwiftLanguageVersion" value="4" />` in your config.xml. Did you try this ?

**Comment by lrbalt** [comment] 2019-03-28 10:53
I do not have this preference in my `config.xml`, but I edited it in Xcode. That works.

I think it is set in the xcode-config if nothing is defined anywhere. I think it is set to 3 on line 148 of `add-swift-support.js` (the one of PR #57). Perhaps it should be changed to 4 since Xcode 10.2 does not support 3 anymore?

**Comment by timbru31** [comment] 2019-03-28 11:06
Yeah you have to add the config setting yourself ;)
I could update my PR to make Swift 4 the new default, since its already introducing breaking changes.

**Comment by byronaltice** [comment] 2019-03-28 13:40
> changing all requireCordovaModule with plain require works. I made a typo, so forget about the other error I reported.

Could you provide me some guidance? I've cloned timbru31's fix, how can I replace the old cordova plugin with the impromptu code?

**Comment by lrbalt** [comment] 2019-03-28 13:49
AFAICS, two options: 

1.  use the PR #57 - I copied all files from that branch to my `plugins/cordova-plugin-add-swift-support`
1. do a search-and-replace for `context.requireCordovaModule` and replace with `require`

The third option is wait for #57 to be merged of course :-)

When everything is merged, you may need to remove the changed plugin and reinstall the official updated plugin

**Comment by byronaltice** [comment] 2019-03-28 14:48
Thanks @lrbalt !

**Closed** 2019-04-01 07:17 UTC

**Comment by lrbalt** [comment] 2019-04-03 11:02
please note that if you manually changed the plugin, it will not be removed using `cordova plugin rm`. It will leave your changed plugin in `plugins/cordova-add-swift-support`. I needed to manually remove it in order to be able to add the newly released plugin.

also, I needed to rebuild the ios workspace by `cordova platform remove ios` and add it again using `cordova platform add ios`. This solved missing method errors in the ios simulator for me for another plugin that uses this one.

**Comment by JPAlfa** [comment] 2019-11-26 14:47
As mentioned on this [Issue](https://github.com/akofman/cordova-plugin-add-swift-support/issues/69), I'm still having problem with this requireCordovaModule. Am I the only one?

**Comment by jfoclpf** [comment] 2020-09-21 10:40
How do I access `require` from the [hooks](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/#sample-usage) script context?

```js
module.exports = function (context) {
  console.log(context.hook)

  var q =  context.requireCordovaModule('q') // does not work
  var q = context.q // does not work
  var q = context.require('q') // does not work
  var q = context.cordova.require('q') // does not work
}
```

Or shall I simply ignore the context altogether in the hooks?

```js
module.exports = function (context) {
  console.log(context.hook)
  var q =  require('q') // this works, but what about the context?
}
```
