### ISSUE TITLE
Error adding cordova-plugin-add-swift-support

### ISSUE THREAD

**Issue by greenlaw110** [akofman/cordova-plugin-add-swift-support#39] opened 2017-09-11 09:23 UTC
```
Joes-MacBook-Pro-2:ui joe$ cordova plugin add cordova-plugin-add-swift-support
Error: Failed to fetch plugin file:node_modules/cordova-plugin-add-swift-support via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm ERR! addLocal Could not install /Users/luog/p/lbb/ui/node_modules/node_modules/cordova-plugin-add-swift-support
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/luog/.nvm/versions/node/v6.11.3/bin/node" "/Users/luog/.nvm/versions/node/v6.11.3/bin/npm" "install" "file:node_modules/cordova-plugin-add-swift-support" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /Users/luog/p/lbb/ui/node_modules/node_modules/cordova-plugin-add-swift-support
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/luog/p/lbb/ui/node_modules/node_modules/cordova-plugin-add-swift-support'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/luog/p/lbb/ui/node_modules/node_modules/cordova-plugin-add-swift-support'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luog/p/lbb/ui/node_modules/npm-debug.log
```

my environment:

```
cli packages: (/Users/joe/.nvm/versions/node/v6.11.3/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : not installed
    Cordova Platforms  : android 6.2.3 ios 4.5.0
    Ionic Framework    : not installed

System:

    ios-deploy : 1.8.5 
    ios-sim    : 5.0.8 
    Node       : v6.11.3
    npm        : 3.10.10 
    OS         : OS X El Capitan
    Xcode      : Xcode 7.3.1 Build version 7D1014 
```

**Comment by sketchthat** [comment] 2017-09-29 03:38
Didn't want to create a new issue as I believe it might be related, but I receive an additional error;

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.
```

**Comment by iamAloTheGreat** [comment] 2017-09-30 13:17
I encountered the same problem and even noticed that by running a command to add a native plugin (e.g fingerprint-aio) the folder `cordova-plugin-add-swift-support` under node_modules became a shortcut.

Just for an info, I solved my problem for the mean time by downgrading Cordova7 to Cordova6 for some research I found out that Cordova7 is now asking package.json file on every plugin. Kindly see this [link](https://cordova.apache.org/news/2017/05/04/cordova-7.html)

**Comment by akofman** [comment] 2017-10-22 18:32
Hello guys, I can't reproduce this issue using Cordova 7.0.1. Could you let me know if you still have it on your side ? 
Also this plugin already have a `package.json` file from the beginning so what will be the fix for that ?

**Comment by akofman** [comment] 2017-12-22 23:01
I close this issue because it is not reproductible since cordova 7.0.1

**Closed by akofman** 2017-12-22 23:01 UTC
